language: go
go:
- '1.11'
git:
  depth: 3
os:
- linux
- osx
env:
  global:
  - GO111MODULE=on
  - secure: H/VTqNb1ODnn6wF5nXq4zWCxFMp4YJbboGfzGAglLHqaqeya2m3YYhjrrVi9BirR4tSoKcNhJwpFgCgrvUURf2h/ML4hckGBR0tokw4OPVHhDq/sbQr5uEyirYIacDkZu8Xo9tTMQuxQLtSmJgvfms2wXP3jdaufK3gpaBA7ma/RVoLEgsZI0pJ0muPcyzdKPA7DLVyHL4C0XaGG+86ch9k79A0+kSklh6ntNtLkzCJwOTMJLraiXbjZYl8HRnt7HhvA97zGrwvqsI9cdlKQo8c9W3zSiV7BZdLZZghhzkz/Yj6jm6Voaa8f2ctoq9OXDMd4gGPMgqnuSfcbVeMd81ZiWNeJw7wnMJcnJm+fQTvOcBvmEAWQo4PanzBl0RFtZdFZy6+GwP5vGiAJb94CV9HKQUyroCkFhKTrZHC5aqgZkKBDaFM8fFSElaANlbU6S39EhgSpSDDGEDA6+DD/5uRWLPeaC9JUZEGUUgv3x3iuAz8IQLGU1v72ZqOj0/m2YRlPI5CFObWPsieciXXn5HOxRBrrHSW6t/c+XuhEEikBtTHA+pfNznbZtXGnCyKhN7L+/ltMC9AQPVbtgL1wjjTpVW0oQRU25PfvxyJnrwpu2wwuLqv5KnbBDuUgXZctufoMhuIL4f0DiQduaXnLajsB615Tin8545DDzemyjZk=
install:
- go mod download
- go install -v github.com/onsi/ginkgo/ginkgo
script:
- go vet ./...
- "./ci/check-fmt.sh"
- "./ci/test.sh"
after_success:
- bash <(curl -s https://codecov.io/bash) -f *.coverprofile
notifications:
  email:
    recipients:
    - ankeesler1@gmail.com
    on_failure: always
