language: go

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3

script:
  - cd storage && go test -coverprofile=cover.out && cd ..
  - cd task && go test -coverprofile=cover.out && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ankeesler1@gmail.com
    on_success: changed
    on_failure: always
