language: go
go:
- '1.11'
git:
  depth: 3
os:
- linux
- osx
env:
  global:
  - GO111MODULE=on
  - secure: d+71ZLqy3/0z7bMgAYkW3glUFqjauESDaRrJuWTB77lhY8PiZljju0oYBowF1W29YkbxfsxfrYb24DqG9I5YvQMFJ3/QVgPMYRl/R6Ch15RTcVKzmTdJ5XkbymW750d8kRHK5f0IzqG9jL8bwlHudjYIKV6BDIerScTB0ujIktPM4p3nBYTcNzMMeISAq1L0N6QuT3009Yq/MO1yBnAE8c/z0q7u4f4lzDWENGmmTl3joqBtGIDQ1VGWSpi7RMsO5hEABWIyQ0cAG5Pgor7gGSWWQI++YxjZcTVG4hs1KoEycWsqOdXW+YSxlHR9lDqWBkq/ouOzwnEqwavwQYmEusUUmrPoX0r9fr2xpWodpuhtq6oG+nroDiRlyZxqqCEqUv8HIGzYdEzDgUkCgSqhh1FJrPx6DzKrcXn3gFVeEpw2KEzNXyLckk/kdSdBBrG0L4r1HUeSgqh8c7kEkcNoGOslc1wp8ObvQD3R/8rzbGg7EmUoW2qAsClXqeDm6uMmzry2zdh4kWpQ5lMDlkKG3iwnDZwytw4CW8+1dNZZH1SAloF0WYeTIBWKiJteDiFl8+WGPYucykm8v4b6gmpjDkjn8uyWF2kCZ6ABchFbueaVs/5yXlXrCpJ/tZMW+6Ua+9peZnSeLvkdemxJ1i3ho1qKU2glALYEC2HDt2mPgPI=
install:
- go mod download
- go install -v github.com/onsi/ginkgo/ginkgo
script:
- go vet ./...
- "./ci/check-fmt.sh"
- "./ci/test.sh"
after_success:
- bash <(curl -s https://codecov.io/bash) -f *.coverprofile
notifications:
  email:
    recipients:
    - ankeesler1@gmail.com
    on_failure: always
