language: go

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3

# Let's skip this for now, since we don't have any dependencies to install.
install: true

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - ankeesler1@gmail.com
    on_success: changed
    on_failure: always
