language: go

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3

install:
  - go get -t -v ./...
  - go install -v github.com/onsi/ginkgo/ginkgo

script:
  - ls $GOPATH/bin
  - ginkgo -r -cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -f *.coverprofile

notifications:
  email:
    recipients:
      - ankeesler1@gmail.com
    on_success: changed
    on_failure: always
