language: go

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3

install:
  - go get -t -v ./...
  - go install -v github.com/onsi/ginkgo/ginkgo

# TODO: run me on Windows as well for better platform coverage! Maybe even Mac as well?

script:
  - go vet ./...
  - o="$(go fmt ./...)"; test -z $o || (echo "The following files are not formatted: $o" && exit 1)
  - ginkgo -r -cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -f *.coverprofile

notifications:
  email:
    recipients:
      - ankeesler1@gmail.com
    on_success: changed
    on_failure: always
