language: java

# I think we can skip the installation step completely because dependencies are
# downloaded automatically as part of our script phase.
install: true

script: ./gradlew smoke

# This takes a little bit of pressure off of the git clone of this repo.
git:
  depth: 3