// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	task.proto

It has these top-level messages:
	Task
	Event
	Journal
	Manager
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_WAITING  State = 0
	State_BLOCKED  State = 1
	State_RUNNING  State = 2
	State_FINISHED State = 3
)

var State_name = map[int32]string{
	0: "WAITING",
	1: "BLOCKED",
	2: "RUNNING",
	3: "FINISHED",
}
var State_value = map[string]int32{
	"WAITING":  0,
	"BLOCKED":  1,
	"RUNNING":  2,
	"FINISHED": 3,
}

func (x State) String() string {
	return proto1.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EventType int32

const (
	EventType_CREATE       EventType = 0
	EventType_DELETE       EventType = 1
	EventType_SET_STATE    EventType = 2
	EventType_NOTE         EventType = 3
	EventType_SET_PRIORITY EventType = 4
)

var EventType_name = map[int32]string{
	0: "CREATE",
	1: "DELETE",
	2: "SET_STATE",
	3: "NOTE",
	4: "SET_PRIORITY",
}
var EventType_value = map[string]int32{
	"CREATE":       0,
	"DELETE":       1,
	"SET_STATE":    2,
	"NOTE":         3,
	"SET_PRIORITY": 4,
}

func (x EventType) String() string {
	return proto1.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Task struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id          int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	StartDate   int64  `protobuf:"varint,4,opt,name=startDate" json:"startDate,omitempty"`
	Priority    int32  `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
	State       State  `protobuf:"varint,6,opt,name=state,enum=State" json:"state,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto1.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *Task) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Task) GetState() State {
	if m != nil {
		return m.State
	}
	return State_WAITING
}

type Event struct {
	Title string    `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Type  EventType `protobuf:"varint,2,opt,name=type,enum=EventType" json:"type,omitempty"`
	Date  int64     `protobuf:"varint,3,opt,name=date" json:"date,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto1.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_CREATE
}

func (m *Event) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type Journal struct {
	Events []*Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *Journal) Reset()                    { *m = Journal{} }
func (m *Journal) String() string            { return proto1.CompactTextString(m) }
func (*Journal) ProtoMessage()               {}
func (*Journal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Journal) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Manager struct {
	Tasks   []*Task  `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	Journal *Journal `protobuf:"bytes,2,opt,name=journal" json:"journal,omitempty"`
}

func (m *Manager) Reset()                    { *m = Manager{} }
func (m *Manager) String() string            { return proto1.CompactTextString(m) }
func (*Manager) ProtoMessage()               {}
func (*Manager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Manager) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Manager) GetJournal() *Journal {
	if m != nil {
		return m.Journal
	}
	return nil
}

func init() {
	proto1.RegisterType((*Task)(nil), "Task")
	proto1.RegisterType((*Event)(nil), "Event")
	proto1.RegisterType((*Journal)(nil), "Journal")
	proto1.RegisterType((*Manager)(nil), "Manager")
	proto1.RegisterEnum("State", State_name, State_value)
	proto1.RegisterEnum("EventType", EventType_name, EventType_value)
}

func init() { proto1.RegisterFile("task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0xc1, 0x8e, 0x94, 0x40,
	0x10, 0xdd, 0x06, 0x1a, 0x66, 0x6a, 0xd6, 0x49, 0xa7, 0xe2, 0x81, 0xe8, 0x66, 0x43, 0x38, 0xe1,
	0x1e, 0x38, 0xe0, 0xd5, 0xcb, 0xee, 0xd2, 0x2a, 0xeb, 0xca, 0x68, 0xd3, 0xc6, 0xe8, 0xc5, 0xb4,
	0xd2, 0x31, 0xb8, 0x2b, 0x10, 0x68, 0x4d, 0xe6, 0x7f, 0xfc, 0x50, 0xd3, 0xcd, 0xce, 0xe8, 0x89,
	0x7a, 0xef, 0x55, 0x3d, 0x5e, 0x55, 0x1a, 0xc0, 0xa8, 0xf9, 0x2e, 0x1f, 0xa7, 0xc1, 0x0c, 0xe9,
	0x1f, 0x02, 0x81, 0x54, 0xf3, 0x1d, 0x22, 0x04, 0xbd, 0xfa, 0xa9, 0x63, 0x92, 0x90, 0x6c, 0x2d,
	0x5c, 0x8d, 0x5b, 0xf0, 0xba, 0x36, 0xf6, 0x12, 0x92, 0x51, 0xe1, 0x75, 0x2d, 0x26, 0xb0, 0x69,
	0xf5, 0xfc, 0x6d, 0xea, 0x46, 0xd3, 0x0d, 0x7d, 0xec, 0xbb, 0xd6, 0xff, 0x29, 0x3c, 0x83, 0xf5,
	0x6c, 0xd4, 0x64, 0x4a, 0x65, 0x74, 0x1c, 0x24, 0x24, 0xf3, 0xc5, 0x3f, 0x02, 0x9f, 0xc0, 0x6a,
	0x9c, 0xba, 0x61, 0xea, 0xcc, 0x3e, 0xa6, 0xce, 0xf5, 0x88, 0xf1, 0x0c, 0xe8, 0x6c, 0xec, 0x54,
	0x98, 0x90, 0x6c, 0x5b, 0x84, 0x79, 0x63, 0x91, 0x58, 0xc8, 0xf4, 0x3d, 0x50, 0xfe, 0x5b, 0xf7,
	0x06, 0x1f, 0x03, 0x35, 0x9d, 0xb9, 0x3f, 0xe4, 0x5c, 0x00, 0x9e, 0x43, 0x60, 0xf6, 0xa3, 0x76,
	0x51, 0xb7, 0x05, 0xe4, 0xae, 0x57, 0xee, 0x47, 0x2d, 0x1c, 0x6f, 0x97, 0x6b, 0xad, 0xb7, 0xef,
	0x12, 0xb9, 0x3a, 0x7d, 0x06, 0xd1, 0xcd, 0xf0, 0x6b, 0xea, 0xd5, 0x3d, 0x9e, 0x43, 0xa8, 0xed,
	0xc4, 0x1c, 0x93, 0xc4, 0xcf, 0x36, 0x45, 0xb8, 0x18, 0x88, 0x07, 0x36, 0xbd, 0x81, 0xe8, 0xad,
	0xea, 0xd5, 0x77, 0x3d, 0xe1, 0x53, 0xa0, 0xf6, 0x7a, 0x87, 0x4e, 0x9a, 0xdb, 0xe3, 0x89, 0x85,
	0xc3, 0x14, 0xa2, 0x1f, 0x8b, 0xa5, 0x4b, 0xb2, 0x29, 0x56, 0xf9, 0xc3, 0x2f, 0xc4, 0x41, 0xb8,
	0x78, 0x01, 0xd4, 0x6d, 0x86, 0x1b, 0x88, 0x3e, 0x5e, 0x56, 0xb2, 0xaa, 0x5f, 0xb1, 0x13, 0x0b,
	0xae, 0x6e, 0x77, 0xd7, 0x6f, 0x78, 0xc9, 0x88, 0x05, 0xe2, 0x43, 0x5d, 0x5b, 0xc5, 0xc3, 0x53,
	0x58, 0xbd, 0xac, 0xea, 0xaa, 0x79, 0xcd, 0x4b, 0xe6, 0x5f, 0xd4, 0xb0, 0x3e, 0xee, 0x86, 0x00,
	0xe1, 0xb5, 0xe0, 0x97, 0x92, 0xb3, 0x13, 0x5b, 0x97, 0xfc, 0x96, 0x4b, 0xce, 0x08, 0x3e, 0x82,
	0x75, 0xc3, 0xe5, 0x97, 0x46, 0x5a, 0xc9, 0xc3, 0x15, 0x04, 0xf5, 0x4e, 0x72, 0xe6, 0x23, 0x83,
	0x53, 0x2b, 0xbc, 0x13, 0xd5, 0x4e, 0x54, 0xf2, 0x13, 0x0b, 0xae, 0xa2, 0xcf, 0xd4, 0xbd, 0x83,
	0xaf, 0xa1, 0xfb, 0x3c, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x13, 0xe8, 0xcb, 0x98, 0x1c, 0x02,
	0x00, 0x00,
}
