// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	task.proto

It has these top-level messages:
	TaskProtobuf
	TaskManagerJournalEntryProtobuf
	TaskManagerJournalProtobuf
	TaskManagerProtobuf
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type StateProtobuf int32

const (
	StateProtobuf_WAITING  StateProtobuf = 0
	StateProtobuf_BLOCKED  StateProtobuf = 1
	StateProtobuf_RUNNING  StateProtobuf = 2
	StateProtobuf_FINISHED StateProtobuf = 3
)

var StateProtobuf_name = map[int32]string{
	0: "WAITING",
	1: "BLOCKED",
	2: "RUNNING",
	3: "FINISHED",
}
var StateProtobuf_value = map[string]int32{
	"WAITING":  0,
	"BLOCKED":  1,
	"RUNNING":  2,
	"FINISHED": 3,
}

func (x StateProtobuf) String() string {
	return proto1.EnumName(StateProtobuf_name, int32(x))
}
func (StateProtobuf) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TaskManagerActionTypeProtobuf int32

const (
	TaskManagerActionTypeProtobuf_CREATE       TaskManagerActionTypeProtobuf = 0
	TaskManagerActionTypeProtobuf_DELETE       TaskManagerActionTypeProtobuf = 1
	TaskManagerActionTypeProtobuf_SET_STATE    TaskManagerActionTypeProtobuf = 2
	TaskManagerActionTypeProtobuf_NOTE         TaskManagerActionTypeProtobuf = 3
	TaskManagerActionTypeProtobuf_SET_PRIORITY TaskManagerActionTypeProtobuf = 4
)

var TaskManagerActionTypeProtobuf_name = map[int32]string{
	0: "CREATE",
	1: "DELETE",
	2: "SET_STATE",
	3: "NOTE",
	4: "SET_PRIORITY",
}
var TaskManagerActionTypeProtobuf_value = map[string]int32{
	"CREATE":       0,
	"DELETE":       1,
	"SET_STATE":    2,
	"NOTE":         3,
	"SET_PRIORITY": 4,
}

func (x TaskManagerActionTypeProtobuf) String() string {
	return proto1.EnumName(TaskManagerActionTypeProtobuf_name, int32(x))
}
func (TaskManagerActionTypeProtobuf) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

type TaskProtobuf struct {
	Name        string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id          int32         `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Description string        `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	StartDate   int64         `protobuf:"varint,4,opt,name=startDate" json:"startDate,omitempty"`
	Priority    int32         `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
	State       StateProtobuf `protobuf:"varint,6,opt,name=state,enum=StateProtobuf" json:"state,omitempty"`
}

func (m *TaskProtobuf) Reset()                    { *m = TaskProtobuf{} }
func (m *TaskProtobuf) String() string            { return proto1.CompactTextString(m) }
func (*TaskProtobuf) ProtoMessage()               {}
func (*TaskProtobuf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TaskProtobuf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskProtobuf) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskProtobuf) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TaskProtobuf) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *TaskProtobuf) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *TaskProtobuf) GetState() StateProtobuf {
	if m != nil {
		return m.State
	}
	return StateProtobuf_WAITING
}

type TaskManagerJournalEntryProtobuf struct {
	Task       *TaskProtobuf                 `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	ActionType TaskManagerActionTypeProtobuf `protobuf:"varint,2,opt,name=actionType,enum=TaskManagerActionTypeProtobuf" json:"actionType,omitempty"`
	Date       int64                         `protobuf:"varint,3,opt,name=date" json:"date,omitempty"`
	Detail     string                        `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
}

func (m *TaskManagerJournalEntryProtobuf) Reset()                    { *m = TaskManagerJournalEntryProtobuf{} }
func (m *TaskManagerJournalEntryProtobuf) String() string            { return proto1.CompactTextString(m) }
func (*TaskManagerJournalEntryProtobuf) ProtoMessage()               {}
func (*TaskManagerJournalEntryProtobuf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TaskManagerJournalEntryProtobuf) GetTask() *TaskProtobuf {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *TaskManagerJournalEntryProtobuf) GetActionType() TaskManagerActionTypeProtobuf {
	if m != nil {
		return m.ActionType
	}
	return TaskManagerActionTypeProtobuf_CREATE
}

func (m *TaskManagerJournalEntryProtobuf) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *TaskManagerJournalEntryProtobuf) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type TaskManagerJournalProtobuf struct {
	Entries []*TaskManagerJournalEntryProtobuf `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *TaskManagerJournalProtobuf) Reset()                    { *m = TaskManagerJournalProtobuf{} }
func (m *TaskManagerJournalProtobuf) String() string            { return proto1.CompactTextString(m) }
func (*TaskManagerJournalProtobuf) ProtoMessage()               {}
func (*TaskManagerJournalProtobuf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TaskManagerJournalProtobuf) GetEntries() []*TaskManagerJournalEntryProtobuf {
	if m != nil {
		return m.Entries
	}
	return nil
}

type TaskManagerProtobuf struct {
	Tasks   []*TaskProtobuf             `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	Journal *TaskManagerJournalProtobuf `protobuf:"bytes,2,opt,name=journal" json:"journal,omitempty"`
}

func (m *TaskManagerProtobuf) Reset()                    { *m = TaskManagerProtobuf{} }
func (m *TaskManagerProtobuf) String() string            { return proto1.CompactTextString(m) }
func (*TaskManagerProtobuf) ProtoMessage()               {}
func (*TaskManagerProtobuf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TaskManagerProtobuf) GetTasks() []*TaskProtobuf {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *TaskManagerProtobuf) GetJournal() *TaskManagerJournalProtobuf {
	if m != nil {
		return m.Journal
	}
	return nil
}

func init() {
	proto1.RegisterType((*TaskProtobuf)(nil), "TaskProtobuf")
	proto1.RegisterType((*TaskManagerJournalEntryProtobuf)(nil), "TaskManagerJournalEntryProtobuf")
	proto1.RegisterType((*TaskManagerJournalProtobuf)(nil), "TaskManagerJournalProtobuf")
	proto1.RegisterType((*TaskManagerProtobuf)(nil), "TaskManagerProtobuf")
	proto1.RegisterEnum("StateProtobuf", StateProtobuf_name, StateProtobuf_value)
	proto1.RegisterEnum("TaskManagerActionTypeProtobuf", TaskManagerActionTypeProtobuf_name, TaskManagerActionTypeProtobuf_value)
}

func init() { proto1.RegisterFile("task.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcb, 0x6f, 0xd3, 0x40,
	0x10, 0xc6, 0xbb, 0x7e, 0xe4, 0x31, 0x4e, 0x22, 0x6b, 0x90, 0x90, 0x55, 0x5e, 0x26, 0x70, 0xb0,
	0x7a, 0xf0, 0xc1, 0x88, 0x0b, 0x07, 0xa4, 0xb4, 0x5e, 0xc0, 0x50, 0x9c, 0x6a, 0xb3, 0x88, 0xc7,
	0x05, 0x6d, 0x6a, 0x83, 0x4c, 0x8b, 0x1d, 0xd6, 0xdb, 0x43, 0xfe, 0x2b, 0x0e, 0xfc, 0x81, 0x68,
	0x37, 0xc4, 0x18, 0x10, 0x70, 0xca, 0x7c, 0xfb, 0xcd, 0x8c, 0xbe, 0xdf, 0xc4, 0x00, 0x4a, 0xb4,
	0x17, 0xf1, 0x46, 0x36, 0xaa, 0x99, 0x7f, 0x23, 0x30, 0xe1, 0xa2, 0xbd, 0x38, 0xd3, 0x6a, 0x7d,
	0xf5, 0x01, 0x11, 0x9c, 0x5a, 0x7c, 0x2e, 0x03, 0x12, 0x92, 0x68, 0xcc, 0x4c, 0x8d, 0x33, 0xb0,
	0xaa, 0x22, 0xb0, 0x42, 0x12, 0xb9, 0xcc, 0xaa, 0x0a, 0x0c, 0xc1, 0x2b, 0xca, 0xf6, 0x5c, 0x56,
	0x1b, 0x55, 0x35, 0x75, 0x60, 0x9b, 0xd6, 0xfe, 0x13, 0xde, 0x84, 0x71, 0xab, 0x84, 0x54, 0xa9,
	0x50, 0x65, 0xe0, 0x84, 0x24, 0xb2, 0xd9, 0xcf, 0x07, 0x3c, 0x84, 0xd1, 0x46, 0x56, 0x8d, 0xac,
	0xd4, 0x36, 0x70, 0xcd, 0xd6, 0x4e, 0xe3, 0x7d, 0x70, 0x5b, 0xa5, 0xa7, 0x06, 0x21, 0x89, 0x66,
	0xc9, 0x2c, 0x5e, 0x69, 0xb5, 0x8f, 0xc7, 0x76, 0xe6, 0xfc, 0x2b, 0x81, 0x3b, 0x3a, 0xf6, 0x4b,
	0x51, 0x8b, 0x8f, 0xa5, 0x7c, 0xde, 0x5c, 0xc9, 0x5a, 0x5c, 0xd2, 0x5a, 0xc9, 0x6d, 0x47, 0x72,
	0x17, 0x1c, 0x0d, 0x6a, 0x48, 0xbc, 0x64, 0x1a, 0xf7, 0x31, 0x99, 0xb1, 0xf0, 0x31, 0x80, 0x38,
	0xd7, 0x81, 0xf9, 0x76, 0x53, 0x1a, 0xc0, 0x59, 0x72, 0x3b, 0xee, 0x2d, 0x5e, 0x74, 0x6e, 0x37,
	0xd9, 0x9b, 0xd0, 0xc7, 0x2a, 0x74, 0x56, 0xdb, 0x10, 0x9a, 0x1a, 0xaf, 0xc3, 0xa0, 0x28, 0x95,
	0xa8, 0x2e, 0x0d, 0xf7, 0x98, 0xfd, 0x50, 0xf3, 0x37, 0x70, 0xf8, 0x67, 0xe2, 0x2e, 0xec, 0x23,
	0x18, 0x96, 0xb5, 0x92, 0x55, 0xd9, 0x06, 0x24, 0xb4, 0x23, 0x2f, 0x09, 0xe3, 0xff, 0xf0, 0xb1,
	0xfd, 0xc0, 0xfc, 0x0b, 0x5c, 0xeb, 0xf5, 0x76, 0x2b, 0xef, 0x81, 0xab, 0x21, 0xf7, 0x0b, 0x7f,
	0x3b, 0xc0, 0xce, 0xc3, 0x87, 0x30, 0xfc, 0xb4, 0x5b, 0x6e, 0xf0, 0xbd, 0xe4, 0x46, 0xfc, 0xf7,
	0x94, 0x6c, 0xdf, 0x7b, 0x94, 0xc2, 0xf4, 0x97, 0xff, 0x05, 0x3d, 0x18, 0xbe, 0x5e, 0x64, 0x3c,
	0xcb, 0x9f, 0xfa, 0x07, 0x5a, 0x1c, 0x9f, 0x2e, 0x4f, 0x5e, 0xd0, 0xd4, 0x27, 0x5a, 0xb0, 0x57,
	0x79, 0xae, 0x1d, 0x0b, 0x27, 0x30, 0x7a, 0x92, 0xe5, 0xd9, 0xea, 0x19, 0x4d, 0x7d, 0xfb, 0x68,
	0x0d, 0xb7, 0xfe, 0x79, 0x6b, 0x04, 0x18, 0x9c, 0x30, 0xba, 0xe0, 0xd4, 0x3f, 0xd0, 0x75, 0x4a,
	0x4f, 0x29, 0xa7, 0x3e, 0xc1, 0x29, 0x8c, 0x57, 0x94, 0xbf, 0x5f, 0x71, 0x6d, 0x59, 0x38, 0x02,
	0x27, 0x5f, 0x72, 0xea, 0xdb, 0xe8, 0xc3, 0x44, 0x1b, 0x67, 0x2c, 0x5b, 0xb2, 0x8c, 0xbf, 0xf5,
	0x9d, 0xe3, 0xe1, 0x3b, 0xd7, 0x7c, 0xe9, 0xeb, 0x81, 0xf9, 0x79, 0xf0, 0x3d, 0x00, 0x00, 0xff,
	0xff, 0x93, 0xdc, 0x09, 0x29, 0xfe, 0x02, 0x00, 0x00,
}
