// This is a very simple application that regenerates the command line interface documentation
// that is used in the anwork (see github.com/ankeesler/anwork/cmd/anwork) application.
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/ankeesler/anwork/cmd/anwork/command"
)

func gendoc(output io.Writer) {
	fmt.Fprintln(output, "Generated by genclidoc. DO NOT EDIT.")
	fmt.Fprintln(output)

	fmt.Fprintln(output, "# _anwork_ CLI commands, version", command.Version)
	fmt.Fprintln(output)

	for _, c := range command.Commands {
		fmt.Fprintf(output, "### `anwork %s", c.Name)
		for _, a := range c.Args {
			fmt.Fprintf(output, " <%s>", a)
		}
		fmt.Fprintln(output, "`")

		fmt.Fprintf(output, "* %s", c.Description)
		fmt.Fprintln(output)
	}
}

func main() {
	output := "../../doc/CLI.md"
	fmt.Printf("Generating documentation into %s ...", output)
	outputFile, err := os.Create(output)
	defer outputFile.Close()
	if err != nil {
		fmt.Printf("Error! %s\n", err.Error())
		os.Exit(1)
	}
	gendoc(outputFile)
	fmt.Println(" done")
}
