resources:
- name: anwork    
  type: git
  source:
    uri: https://github.com/ankeesler/anwork
    branch: master

jobs:
- name: tests
  plan:
  - get: anwork
    trigger: true
  - task: tests
    file: ci/tests.yml

